services:
  - type: web
    name: kwill
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
